/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccountsPayableRouteImport } from './routes/accounts-payable'
import { Route as AccountsReceivableRouteImport } from './routes/accounts-receivable'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdjustmentsRouteImport } from './routes/adjustments'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BankAccountsRouteImport } from './routes/bank-accounts'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CostCentersRouteImport } from './routes/cost-centers'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CrmTagsRouteImport } from './routes/crm-tags'
import { Route as CustomerPaymentsRouteImport } from './routes/customer-payments'
import { Route as CustomerSegmentsRouteImport } from './routes/customer-segments'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DeliveryNotesRouteImport } from './routes/delivery-notes'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FinancialReportsRouteImport } from './routes/financial-reports'
import { Route as FiscalYearsRouteImport } from './routes/fiscal-years'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GoodsReceiptsRouteImport } from './routes/goods-receipts'
import { Route as GradientBlurDemoRouteImport } from './routes/gradient-blur-demo'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as JournalEntriesRouteImport } from './routes/journal-entries'
import { Route as LandedCostsRouteImport } from './routes/landed-costs'
import { Route as LeadSourcesRouteImport } from './routes/lead-sources'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as PurchaseRequestsRouteImport } from './routes/purchase-requests'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SalesCreditNotesRouteImport } from './routes/sales-credit-notes'
import { Route as SalesInvoicesRouteImport } from './routes/sales-invoices'
import { Route as SalesOrdersRouteImport } from './routes/sales-orders'
import { Route as SalesReturnsRouteImport } from './routes/sales-returns'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SerialNumbersRouteImport } from './routes/serial-numbers'
import { Route as SupplierInvoicesRouteImport } from './routes/supplier-invoices'
import { Route as SupplierPaymentsRouteImport } from './routes/supplier-payments'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TaxReportsRouteImport } from './routes/tax-reports'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as StatesEmptyRouteImport } from './routes/states/empty'
import { Route as StatesErrorRouteImport } from './routes/states/error'
import { Route as StatesLoadingRouteImport } from './routes/states/loading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsPayableRoute = AccountsPayableRouteImport.update({
  id: '/accounts-payable',
  path: '/accounts-payable',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsReceivableRoute = AccountsReceivableRouteImport.update({
  id: '/accounts-receivable',
  path: '/accounts-receivable',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsRoute = AdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsRoute = BankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CostCentersRoute = CostCentersRouteImport.update({
  id: '/cost-centers',
  path: '/cost-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmTagsRoute = CrmTagsRouteImport.update({
  id: '/crm-tags',
  path: '/crm-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPaymentsRoute = CustomerPaymentsRouteImport.update({
  id: '/customer-payments',
  path: '/customer-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSegmentsRoute = CustomerSegmentsRouteImport.update({
  id: '/customer-segments',
  path: '/customer-segments',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryNotesRoute = DeliveryNotesRouteImport.update({
  id: '/delivery-notes',
  path: '/delivery-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialReportsRoute = FinancialReportsRouteImport.update({
  id: '/financial-reports',
  path: '/financial-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalYearsRoute = FiscalYearsRouteImport.update({
  id: '/fiscal-years',
  path: '/fiscal-years',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsReceiptsRoute = GoodsReceiptsRouteImport.update({
  id: '/goods-receipts',
  path: '/goods-receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientBlurDemoRoute = GradientBlurDemoRouteImport.update({
  id: '/gradient-blur-demo',
  path: '/gradient-blur-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntriesRoute = JournalEntriesRouteImport.update({
  id: '/journal-entries',
  path: '/journal-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const LandedCostsRoute = LandedCostsRouteImport.update({
  id: '/landed-costs',
  path: '/landed-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadSourcesRoute = LeadSourcesRouteImport.update({
  id: '/lead-sources',
  path: '/lead-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsRoute = PurchaseRequestsRouteImport.update({
  id: '/purchase-requests',
  path: '/purchase-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCreditNotesRoute = SalesCreditNotesRouteImport.update({
  id: '/sales-credit-notes',
  path: '/sales-credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicesRoute = SalesInvoicesRouteImport.update({
  id: '/sales-invoices',
  path: '/sales-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReturnsRoute = SalesReturnsRouteImport.update({
  id: '/sales-returns',
  path: '/sales-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SerialNumbersRoute = SerialNumbersRouteImport.update({
  id: '/serial-numbers',
  path: '/serial-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierInvoicesRoute = SupplierInvoicesRouteImport.update({
  id: '/supplier-invoices',
  path: '/supplier-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPaymentsRoute = SupplierPaymentsRouteImport.update({
  id: '/supplier-payments',
  path: '/supplier-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxReportsRoute = TaxReportsRouteImport.update({
  id: '/tax-reports',
  path: '/tax-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesEmptyRoute = StatesEmptyRouteImport.update({
  id: '/states/empty',
  path: '/states/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesErrorRoute = StatesErrorRouteImport.update({
  id: '/states/error',
  path: '/states/error',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesLoadingRoute = StatesLoadingRouteImport.update({
  id: '/states/loading',
  path: '/states/loading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/accounts': typeof AccountsRoute
  '/accounts-payable': typeof AccountsPayableRoute
  '/accounts-receivable': typeof AccountsReceivableRoute
  '/activities': typeof ActivitiesRoute
  '/activity': typeof ActivityRoute
  '/adjustments': typeof AdjustmentsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/batches': typeof BatchesRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contacts': typeof ContactsRoute
  '/cost-centers': typeof CostCentersRoute
  '/crm': typeof CrmRoute
  '/crm-tags': typeof CrmTagsRoute
  '/customer-payments': typeof CustomerPaymentsRoute
  '/customer-segments': typeof CustomerSegmentsRoute
  '/customers': typeof CustomersRoute
  '/delivery-notes': typeof DeliveryNotesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/fiscal-years': typeof FiscalYearsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goods-receipts': typeof GoodsReceiptsRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/landed-costs': typeof LandedCostsRoute
  '/lead-sources': typeof LeadSourcesRoute
  '/leads': typeof LeadsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/pipelines': typeof PipelinesRoute
  '/pos': typeof PosRoute
  '/preferences': typeof PreferencesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchase-requests': typeof PurchaseRequestsRoute
  '/purchasing': typeof PurchasingRoute
  '/quotations': typeof QuotationsRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sales': typeof SalesRoute
  '/sales-credit-notes': typeof SalesCreditNotesRoute
  '/sales-invoices': typeof SalesInvoicesRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/search': typeof SearchRoute
  '/serial-numbers': typeof SerialNumbersRoute
  '/supplier-invoices': typeof SupplierInvoicesRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/tax-reports': typeof TaxReportsRoute
  '/taxes': typeof TaxesRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/accounts': typeof AccountsRoute
  '/accounts-payable': typeof AccountsPayableRoute
  '/accounts-receivable': typeof AccountsReceivableRoute
  '/activities': typeof ActivitiesRoute
  '/activity': typeof ActivityRoute
  '/adjustments': typeof AdjustmentsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/batches': typeof BatchesRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contacts': typeof ContactsRoute
  '/cost-centers': typeof CostCentersRoute
  '/crm': typeof CrmRoute
  '/crm-tags': typeof CrmTagsRoute
  '/customer-payments': typeof CustomerPaymentsRoute
  '/customer-segments': typeof CustomerSegmentsRoute
  '/customers': typeof CustomersRoute
  '/delivery-notes': typeof DeliveryNotesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/fiscal-years': typeof FiscalYearsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goods-receipts': typeof GoodsReceiptsRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/landed-costs': typeof LandedCostsRoute
  '/lead-sources': typeof LeadSourcesRoute
  '/leads': typeof LeadsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/pipelines': typeof PipelinesRoute
  '/pos': typeof PosRoute
  '/preferences': typeof PreferencesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchase-requests': typeof PurchaseRequestsRoute
  '/purchasing': typeof PurchasingRoute
  '/quotations': typeof QuotationsRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sales': typeof SalesRoute
  '/sales-credit-notes': typeof SalesCreditNotesRoute
  '/sales-invoices': typeof SalesInvoicesRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/search': typeof SearchRoute
  '/serial-numbers': typeof SerialNumbersRoute
  '/supplier-invoices': typeof SupplierInvoicesRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/tax-reports': typeof TaxReportsRoute
  '/taxes': typeof TaxesRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/accounts': typeof AccountsRoute
  '/accounts-payable': typeof AccountsPayableRoute
  '/accounts-receivable': typeof AccountsReceivableRoute
  '/activities': typeof ActivitiesRoute
  '/activity': typeof ActivityRoute
  '/adjustments': typeof AdjustmentsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bank-accounts': typeof BankAccountsRoute
  '/batches': typeof BatchesRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contacts': typeof ContactsRoute
  '/cost-centers': typeof CostCentersRoute
  '/crm': typeof CrmRoute
  '/crm-tags': typeof CrmTagsRoute
  '/customer-payments': typeof CustomerPaymentsRoute
  '/customer-segments': typeof CustomerSegmentsRoute
  '/customers': typeof CustomersRoute
  '/delivery-notes': typeof DeliveryNotesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/financial-reports': typeof FinancialReportsRoute
  '/fiscal-years': typeof FiscalYearsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goods-receipts': typeof GoodsReceiptsRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/landed-costs': typeof LandedCostsRoute
  '/lead-sources': typeof LeadSourcesRoute
  '/leads': typeof LeadsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/notes': typeof NotesRoute
  '/notifications': typeof NotificationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/pipelines': typeof PipelinesRoute
  '/pos': typeof PosRoute
  '/preferences': typeof PreferencesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/purchase-requests': typeof PurchaseRequestsRoute
  '/purchasing': typeof PurchasingRoute
  '/quotations': typeof QuotationsRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/sales': typeof SalesRoute
  '/sales-credit-notes': typeof SalesCreditNotesRoute
  '/sales-invoices': typeof SalesInvoicesRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/search': typeof SearchRoute
  '/serial-numbers': typeof SerialNumbersRoute
  '/supplier-invoices': typeof SupplierInvoicesRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/tax-reports': typeof TaxReportsRoute
  '/taxes': typeof TaxesRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/accounts'
    | '/accounts-payable'
    | '/accounts-receivable'
    | '/activities'
    | '/activity'
    | '/adjustments'
    | '/audit-logs'
    | '/bank-accounts'
    | '/batches'
    | '/branches'
    | '/brands'
    | '/categories'
    | '/contacts'
    | '/cost-centers'
    | '/crm'
    | '/crm-tags'
    | '/customer-payments'
    | '/customer-segments'
    | '/customers'
    | '/delivery-notes'
    | '/departments'
    | '/files'
    | '/financial-reports'
    | '/fiscal-years'
    | '/forgot-password'
    | '/goods-receipts'
    | '/gradient-blur-demo'
    | '/help'
    | '/inventory'
    | '/journal-entries'
    | '/landed-costs'
    | '/lead-sources'
    | '/leads'
    | '/locations'
    | '/login'
    | '/movements'
    | '/notes'
    | '/notifications'
    | '/opportunities'
    | '/organization'
    | '/permissions'
    | '/pipelines'
    | '/pos'
    | '/preferences'
    | '/products'
    | '/profile'
    | '/purchase-orders'
    | '/purchase-requests'
    | '/purchasing'
    | '/quotations'
    | '/reservations'
    | '/reset-password'
    | '/roles'
    | '/sales'
    | '/sales-credit-notes'
    | '/sales-invoices'
    | '/sales-orders'
    | '/sales-returns'
    | '/search'
    | '/serial-numbers'
    | '/supplier-invoices'
    | '/supplier-payments'
    | '/suppliers'
    | '/tasks'
    | '/tax-reports'
    | '/taxes'
    | '/teams'
    | '/transfers'
    | '/units'
    | '/users'
    | '/warehouses'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/accounts'
    | '/accounts-payable'
    | '/accounts-receivable'
    | '/activities'
    | '/activity'
    | '/adjustments'
    | '/audit-logs'
    | '/bank-accounts'
    | '/batches'
    | '/branches'
    | '/brands'
    | '/categories'
    | '/contacts'
    | '/cost-centers'
    | '/crm'
    | '/crm-tags'
    | '/customer-payments'
    | '/customer-segments'
    | '/customers'
    | '/delivery-notes'
    | '/departments'
    | '/files'
    | '/financial-reports'
    | '/fiscal-years'
    | '/forgot-password'
    | '/goods-receipts'
    | '/gradient-blur-demo'
    | '/help'
    | '/inventory'
    | '/journal-entries'
    | '/landed-costs'
    | '/lead-sources'
    | '/leads'
    | '/locations'
    | '/login'
    | '/movements'
    | '/notes'
    | '/notifications'
    | '/opportunities'
    | '/organization'
    | '/permissions'
    | '/pipelines'
    | '/pos'
    | '/preferences'
    | '/products'
    | '/profile'
    | '/purchase-orders'
    | '/purchase-requests'
    | '/purchasing'
    | '/quotations'
    | '/reservations'
    | '/reset-password'
    | '/roles'
    | '/sales'
    | '/sales-credit-notes'
    | '/sales-invoices'
    | '/sales-orders'
    | '/sales-returns'
    | '/search'
    | '/serial-numbers'
    | '/supplier-invoices'
    | '/supplier-payments'
    | '/suppliers'
    | '/tasks'
    | '/tax-reports'
    | '/taxes'
    | '/teams'
    | '/transfers'
    | '/units'
    | '/users'
    | '/warehouses'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/accounts'
    | '/accounts-payable'
    | '/accounts-receivable'
    | '/activities'
    | '/activity'
    | '/adjustments'
    | '/audit-logs'
    | '/bank-accounts'
    | '/batches'
    | '/branches'
    | '/brands'
    | '/categories'
    | '/contacts'
    | '/cost-centers'
    | '/crm'
    | '/crm-tags'
    | '/customer-payments'
    | '/customer-segments'
    | '/customers'
    | '/delivery-notes'
    | '/departments'
    | '/files'
    | '/financial-reports'
    | '/fiscal-years'
    | '/forgot-password'
    | '/goods-receipts'
    | '/gradient-blur-demo'
    | '/help'
    | '/inventory'
    | '/journal-entries'
    | '/landed-costs'
    | '/lead-sources'
    | '/leads'
    | '/locations'
    | '/login'
    | '/movements'
    | '/notes'
    | '/notifications'
    | '/opportunities'
    | '/organization'
    | '/permissions'
    | '/pipelines'
    | '/pos'
    | '/preferences'
    | '/products'
    | '/profile'
    | '/purchase-orders'
    | '/purchase-requests'
    | '/purchasing'
    | '/quotations'
    | '/reservations'
    | '/reset-password'
    | '/roles'
    | '/sales'
    | '/sales-credit-notes'
    | '/sales-invoices'
    | '/sales-orders'
    | '/sales-returns'
    | '/search'
    | '/serial-numbers'
    | '/supplier-invoices'
    | '/supplier-payments'
    | '/suppliers'
    | '/tasks'
    | '/tax-reports'
    | '/taxes'
    | '/teams'
    | '/transfers'
    | '/units'
    | '/users'
    | '/warehouses'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AccountsRoute: typeof AccountsRoute
  AccountsPayableRoute: typeof AccountsPayableRoute
  AccountsReceivableRoute: typeof AccountsReceivableRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ActivityRoute: typeof ActivityRoute
  AdjustmentsRoute: typeof AdjustmentsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BankAccountsRoute: typeof BankAccountsRoute
  BatchesRoute: typeof BatchesRoute
  BranchesRoute: typeof BranchesRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactsRoute: typeof ContactsRoute
  CostCentersRoute: typeof CostCentersRoute
  CrmRoute: typeof CrmRoute
  CrmTagsRoute: typeof CrmTagsRoute
  CustomerPaymentsRoute: typeof CustomerPaymentsRoute
  CustomerSegmentsRoute: typeof CustomerSegmentsRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryNotesRoute: typeof DeliveryNotesRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FilesRoute: typeof FilesRoute
  FinancialReportsRoute: typeof FinancialReportsRoute
  FiscalYearsRoute: typeof FiscalYearsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoodsReceiptsRoute: typeof GoodsReceiptsRoute
  GradientBlurDemoRoute: typeof GradientBlurDemoRoute
  HelpRoute: typeof HelpRoute
  InventoryRoute: typeof InventoryRoute
  JournalEntriesRoute: typeof JournalEntriesRoute
  LandedCostsRoute: typeof LandedCostsRoute
  LeadSourcesRoute: typeof LeadSourcesRoute
  LeadsRoute: typeof LeadsRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  MovementsRoute: typeof MovementsRoute
  NotesRoute: typeof NotesRoute
  NotificationsRoute: typeof NotificationsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OrganizationRoute: typeof OrganizationRoute
  PermissionsRoute: typeof PermissionsRoute
  PipelinesRoute: typeof PipelinesRoute
  PosRoute: typeof PosRoute
  PreferencesRoute: typeof PreferencesRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  PurchaseRequestsRoute: typeof PurchaseRequestsRoute
  PurchasingRoute: typeof PurchasingRoute
  QuotationsRoute: typeof QuotationsRoute
  ReservationsRoute: typeof ReservationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SalesRoute: typeof SalesRoute
  SalesCreditNotesRoute: typeof SalesCreditNotesRoute
  SalesInvoicesRoute: typeof SalesInvoicesRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
  SalesReturnsRoute: typeof SalesReturnsRoute
  SearchRoute: typeof SearchRoute
  SerialNumbersRoute: typeof SerialNumbersRoute
  SupplierInvoicesRoute: typeof SupplierInvoicesRoute
  SupplierPaymentsRoute: typeof SupplierPaymentsRoute
  SuppliersRoute: typeof SuppliersRoute
  TasksRoute: typeof TasksRoute
  TaxReportsRoute: typeof TaxReportsRoute
  TaxesRoute: typeof TaxesRoute
  TeamsRoute: typeof TeamsRoute
  TransfersRoute: typeof TransfersRoute
  UnitsRoute: typeof UnitsRoute
  UsersRoute: typeof UsersRoute
  WarehousesRoute: typeof WarehousesRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  StatesEmptyRoute: typeof StatesEmptyRoute
  StatesErrorRoute: typeof StatesErrorRoute
  StatesLoadingRoute: typeof StatesLoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-payable': {
      id: '/accounts-payable'
      path: '/accounts-payable'
      fullPath: '/accounts-payable'
      preLoaderRoute: typeof AccountsPayableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-receivable': {
      id: '/accounts-receivable'
      path: '/accounts-receivable'
      fullPath: '/accounts-receivable'
      preLoaderRoute: typeof AccountsReceivableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments': {
      id: '/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts': {
      id: '/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/bank-accounts'
      preLoaderRoute: typeof BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-centers': {
      id: '/cost-centers'
      path: '/cost-centers'
      fullPath: '/cost-centers'
      preLoaderRoute: typeof CostCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-tags': {
      id: '/crm-tags'
      path: '/crm-tags'
      fullPath: '/crm-tags'
      preLoaderRoute: typeof CrmTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-payments': {
      id: '/customer-payments'
      path: '/customer-payments'
      fullPath: '/customer-payments'
      preLoaderRoute: typeof CustomerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-segments': {
      id: '/customer-segments'
      path: '/customer-segments'
      fullPath: '/customer-segments'
      preLoaderRoute: typeof CustomerSegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-notes': {
      id: '/delivery-notes'
      path: '/delivery-notes'
      fullPath: '/delivery-notes'
      preLoaderRoute: typeof DeliveryNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-reports': {
      id: '/financial-reports'
      path: '/financial-reports'
      fullPath: '/financial-reports'
      preLoaderRoute: typeof FinancialReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal-years': {
      id: '/fiscal-years'
      path: '/fiscal-years'
      fullPath: '/fiscal-years'
      preLoaderRoute: typeof FiscalYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods-receipts': {
      id: '/goods-receipts'
      path: '/goods-receipts'
      fullPath: '/goods-receipts'
      preLoaderRoute: typeof GoodsReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient-blur-demo': {
      id: '/gradient-blur-demo'
      path: '/gradient-blur-demo'
      fullPath: '/gradient-blur-demo'
      preLoaderRoute: typeof GradientBlurDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-entries': {
      id: '/journal-entries'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof JournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landed-costs': {
      id: '/landed-costs'
      path: '/landed-costs'
      fullPath: '/landed-costs'
      preLoaderRoute: typeof LandedCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-sources': {
      id: '/lead-sources'
      path: '/lead-sources'
      fullPath: '/lead-sources'
      preLoaderRoute: typeof LeadSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests': {
      id: '/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/purchase-requests'
      preLoaderRoute: typeof PurchaseRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-credit-notes': {
      id: '/sales-credit-notes'
      path: '/sales-credit-notes'
      fullPath: '/sales-credit-notes'
      preLoaderRoute: typeof SalesCreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-invoices': {
      id: '/sales-invoices'
      path: '/sales-invoices'
      fullPath: '/sales-invoices'
      preLoaderRoute: typeof SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders': {
      id: '/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-returns': {
      id: '/sales-returns'
      path: '/sales-returns'
      fullPath: '/sales-returns'
      preLoaderRoute: typeof SalesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serial-numbers': {
      id: '/serial-numbers'
      path: '/serial-numbers'
      fullPath: '/serial-numbers'
      preLoaderRoute: typeof SerialNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-invoices': {
      id: '/supplier-invoices'
      path: '/supplier-invoices'
      fullPath: '/supplier-invoices'
      preLoaderRoute: typeof SupplierInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-payments': {
      id: '/supplier-payments'
      path: '/supplier-payments'
      fullPath: '/supplier-payments'
      preLoaderRoute: typeof SupplierPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-reports': {
      id: '/tax-reports'
      path: '/tax-reports'
      fullPath: '/tax-reports'
      preLoaderRoute: typeof TaxReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/empty': {
      id: '/states/empty'
      path: '/states/empty'
      fullPath: '/states/empty'
      preLoaderRoute: typeof StatesEmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/error': {
      id: '/states/error'
      path: '/states/error'
      fullPath: '/states/error'
      preLoaderRoute: typeof StatesErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/loading': {
      id: '/states/loading'
      path: '/states/loading'
      fullPath: '/states/loading'
      preLoaderRoute: typeof StatesLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AccountsRoute: AccountsRoute,
  AccountsPayableRoute: AccountsPayableRoute,
  AccountsReceivableRoute: AccountsReceivableRoute,
  ActivitiesRoute: ActivitiesRoute,
  ActivityRoute: ActivityRoute,
  AdjustmentsRoute: AdjustmentsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BankAccountsRoute: BankAccountsRoute,
  BatchesRoute: BatchesRoute,
  BranchesRoute: BranchesRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  ContactsRoute: ContactsRoute,
  CostCentersRoute: CostCentersRoute,
  CrmRoute: CrmRoute,
  CrmTagsRoute: CrmTagsRoute,
  CustomerPaymentsRoute: CustomerPaymentsRoute,
  CustomerSegmentsRoute: CustomerSegmentsRoute,
  CustomersRoute: CustomersRoute,
  DeliveryNotesRoute: DeliveryNotesRoute,
  DepartmentsRoute: DepartmentsRoute,
  FilesRoute: FilesRoute,
  FinancialReportsRoute: FinancialReportsRoute,
  FiscalYearsRoute: FiscalYearsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoodsReceiptsRoute: GoodsReceiptsRoute,
  GradientBlurDemoRoute: GradientBlurDemoRoute,
  HelpRoute: HelpRoute,
  InventoryRoute: InventoryRoute,
  JournalEntriesRoute: JournalEntriesRoute,
  LandedCostsRoute: LandedCostsRoute,
  LeadSourcesRoute: LeadSourcesRoute,
  LeadsRoute: LeadsRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  MovementsRoute: MovementsRoute,
  NotesRoute: NotesRoute,
  NotificationsRoute: NotificationsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OrganizationRoute: OrganizationRoute,
  PermissionsRoute: PermissionsRoute,
  PipelinesRoute: PipelinesRoute,
  PosRoute: PosRoute,
  PreferencesRoute: PreferencesRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  PurchaseRequestsRoute: PurchaseRequestsRoute,
  PurchasingRoute: PurchasingRoute,
  QuotationsRoute: QuotationsRoute,
  ReservationsRoute: ReservationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SalesRoute: SalesRoute,
  SalesCreditNotesRoute: SalesCreditNotesRoute,
  SalesInvoicesRoute: SalesInvoicesRoute,
  SalesOrdersRoute: SalesOrdersRoute,
  SalesReturnsRoute: SalesReturnsRoute,
  SearchRoute: SearchRoute,
  SerialNumbersRoute: SerialNumbersRoute,
  SupplierInvoicesRoute: SupplierInvoicesRoute,
  SupplierPaymentsRoute: SupplierPaymentsRoute,
  SuppliersRoute: SuppliersRoute,
  TasksRoute: TasksRoute,
  TaxReportsRoute: TaxReportsRoute,
  TaxesRoute: TaxesRoute,
  TeamsRoute: TeamsRoute,
  TransfersRoute: TransfersRoute,
  UnitsRoute: UnitsRoute,
  UsersRoute: UsersRoute,
  WarehousesRoute: WarehousesRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  StatesEmptyRoute: StatesEmptyRoute,
  StatesErrorRoute: StatesErrorRoute,
  StatesLoadingRoute: StatesLoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
