/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdjustmentsRouteImport } from './routes/adjustments'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GradientBlurDemoRouteImport } from './routes/gradient-blur-demo'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SerialNumbersRouteImport } from './routes/serial-numbers'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as StatesEmptyRouteImport } from './routes/states/empty'
import { Route as StatesErrorRouteImport } from './routes/states/error'
import { Route as StatesLoadingRouteImport } from './routes/states/loading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentsRoute = AdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientBlurDemoRoute = GradientBlurDemoRouteImport.update({
  id: '/gradient-blur-demo',
  path: '/gradient-blur-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SerialNumbersRoute = SerialNumbersRouteImport.update({
  id: '/serial-numbers',
  path: '/serial-numbers',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesEmptyRoute = StatesEmptyRouteImport.update({
  id: '/states/empty',
  path: '/states/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesErrorRoute = StatesErrorRouteImport.update({
  id: '/states/error',
  path: '/states/error',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesLoadingRoute = StatesLoadingRouteImport.update({
  id: '/states/loading',
  path: '/states/loading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/adjustments': typeof AdjustmentsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/batches': typeof BatchesRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/preferences': typeof PreferencesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/search': typeof SearchRoute
  '/serial-numbers': typeof SerialNumbersRoute
  '/taxes': typeof TaxesRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/adjustments': typeof AdjustmentsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/batches': typeof BatchesRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/preferences': typeof PreferencesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/search': typeof SearchRoute
  '/serial-numbers': typeof SerialNumbersRoute
  '/taxes': typeof TaxesRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/adjustments': typeof AdjustmentsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/batches': typeof BatchesRoute
  '/branches': typeof BranchesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/movements': typeof MovementsRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/preferences': typeof PreferencesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reservations': typeof ReservationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/search': typeof SearchRoute
  '/serial-numbers': typeof SerialNumbersRoute
  '/taxes': typeof TaxesRoute
  '/teams': typeof TeamsRoute
  '/transfers': typeof TransfersRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/adjustments'
    | '/audit-logs'
    | '/batches'
    | '/branches'
    | '/brands'
    | '/categories'
    | '/departments'
    | '/files'
    | '/forgot-password'
    | '/gradient-blur-demo'
    | '/help'
    | '/inventory'
    | '/locations'
    | '/login'
    | '/movements'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/preferences'
    | '/products'
    | '/profile'
    | '/reservations'
    | '/reset-password'
    | '/roles'
    | '/search'
    | '/serial-numbers'
    | '/taxes'
    | '/teams'
    | '/transfers'
    | '/units'
    | '/users'
    | '/warehouses'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/adjustments'
    | '/audit-logs'
    | '/batches'
    | '/branches'
    | '/brands'
    | '/categories'
    | '/departments'
    | '/files'
    | '/forgot-password'
    | '/gradient-blur-demo'
    | '/help'
    | '/inventory'
    | '/locations'
    | '/login'
    | '/movements'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/preferences'
    | '/products'
    | '/profile'
    | '/reservations'
    | '/reset-password'
    | '/roles'
    | '/search'
    | '/serial-numbers'
    | '/taxes'
    | '/teams'
    | '/transfers'
    | '/units'
    | '/users'
    | '/warehouses'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/adjustments'
    | '/audit-logs'
    | '/batches'
    | '/branches'
    | '/brands'
    | '/categories'
    | '/departments'
    | '/files'
    | '/forgot-password'
    | '/gradient-blur-demo'
    | '/help'
    | '/inventory'
    | '/locations'
    | '/login'
    | '/movements'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/preferences'
    | '/products'
    | '/profile'
    | '/reservations'
    | '/reset-password'
    | '/roles'
    | '/search'
    | '/serial-numbers'
    | '/taxes'
    | '/teams'
    | '/transfers'
    | '/units'
    | '/users'
    | '/warehouses'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdjustmentsRoute: typeof AdjustmentsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BatchesRoute: typeof BatchesRoute
  BranchesRoute: typeof BranchesRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FilesRoute: typeof FilesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GradientBlurDemoRoute: typeof GradientBlurDemoRoute
  HelpRoute: typeof HelpRoute
  InventoryRoute: typeof InventoryRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  MovementsRoute: typeof MovementsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationRoute: typeof OrganizationRoute
  PermissionsRoute: typeof PermissionsRoute
  PreferencesRoute: typeof PreferencesRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ReservationsRoute: typeof ReservationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SearchRoute: typeof SearchRoute
  SerialNumbersRoute: typeof SerialNumbersRoute
  TaxesRoute: typeof TaxesRoute
  TeamsRoute: typeof TeamsRoute
  TransfersRoute: typeof TransfersRoute
  UnitsRoute: typeof UnitsRoute
  UsersRoute: typeof UsersRoute
  WarehousesRoute: typeof WarehousesRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  StatesEmptyRoute: typeof StatesEmptyRoute
  StatesErrorRoute: typeof StatesErrorRoute
  StatesLoadingRoute: typeof StatesLoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustments': {
      id: '/adjustments'
      path: '/adjustments'
      fullPath: '/adjustments'
      preLoaderRoute: typeof AdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient-blur-demo': {
      id: '/gradient-blur-demo'
      path: '/gradient-blur-demo'
      fullPath: '/gradient-blur-demo'
      preLoaderRoute: typeof GradientBlurDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serial-numbers': {
      id: '/serial-numbers'
      path: '/serial-numbers'
      fullPath: '/serial-numbers'
      preLoaderRoute: typeof SerialNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/empty': {
      id: '/states/empty'
      path: '/states/empty'
      fullPath: '/states/empty'
      preLoaderRoute: typeof StatesEmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/error': {
      id: '/states/error'
      path: '/states/error'
      fullPath: '/states/error'
      preLoaderRoute: typeof StatesErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/loading': {
      id: '/states/loading'
      path: '/states/loading'
      fullPath: '/states/loading'
      preLoaderRoute: typeof StatesLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdjustmentsRoute: AdjustmentsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BatchesRoute: BatchesRoute,
  BranchesRoute: BranchesRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  DepartmentsRoute: DepartmentsRoute,
  FilesRoute: FilesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GradientBlurDemoRoute: GradientBlurDemoRoute,
  HelpRoute: HelpRoute,
  InventoryRoute: InventoryRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  MovementsRoute: MovementsRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationRoute: OrganizationRoute,
  PermissionsRoute: PermissionsRoute,
  PreferencesRoute: PreferencesRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ReservationsRoute: ReservationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SearchRoute: SearchRoute,
  SerialNumbersRoute: SerialNumbersRoute,
  TaxesRoute: TaxesRoute,
  TeamsRoute: TeamsRoute,
  TransfersRoute: TransfersRoute,
  UnitsRoute: UnitsRoute,
  UsersRoute: UsersRoute,
  WarehousesRoute: WarehousesRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  StatesEmptyRoute: StatesEmptyRoute,
  StatesErrorRoute: StatesErrorRoute,
  StatesLoadingRoute: StatesLoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
