/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GradientBlurDemoRouteImport } from './routes/gradient-blur-demo'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as StatesEmptyRouteImport } from './routes/states/empty'
import { Route as StatesErrorRouteImport } from './routes/states/error'
import { Route as StatesLoadingRouteImport } from './routes/states/loading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientBlurDemoRoute = GradientBlurDemoRouteImport.update({
  id: '/gradient-blur-demo',
  path: '/gradient-blur-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesEmptyRoute = StatesEmptyRouteImport.update({
  id: '/states/empty',
  path: '/states/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesErrorRoute = StatesErrorRouteImport.update({
  id: '/states/error',
  path: '/states/error',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesLoadingRoute = StatesLoadingRouteImport.update({
  id: '/states/loading',
  path: '/states/loading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/audit-logs': typeof AuditLogsRoute
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/search': typeof SearchRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/audit-logs': typeof AuditLogsRoute
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/search': typeof SearchRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/audit-logs': typeof AuditLogsRoute
  '/branches': typeof BranchesRoute
  '/departments': typeof DepartmentsRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gradient-blur-demo': typeof GradientBlurDemoRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/permissions': typeof PermissionsRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/search': typeof SearchRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/states/empty': typeof StatesEmptyRoute
  '/states/error': typeof StatesErrorRoute
  '/states/loading': typeof StatesLoadingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/audit-logs'
    | '/branches'
    | '/departments'
    | '/files'
    | '/forgot-password'
    | '/gradient-blur-demo'
    | '/help'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/preferences'
    | '/profile'
    | '/reset-password'
    | '/roles'
    | '/search'
    | '/teams'
    | '/users'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/audit-logs'
    | '/branches'
    | '/departments'
    | '/files'
    | '/forgot-password'
    | '/gradient-blur-demo'
    | '/help'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/preferences'
    | '/profile'
    | '/reset-password'
    | '/roles'
    | '/search'
    | '/teams'
    | '/users'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/audit-logs'
    | '/branches'
    | '/departments'
    | '/files'
    | '/forgot-password'
    | '/gradient-blur-demo'
    | '/help'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/permissions'
    | '/preferences'
    | '/profile'
    | '/reset-password'
    | '/roles'
    | '/search'
    | '/teams'
    | '/users'
    | '/settings/appearance'
    | '/settings/security'
    | '/settings/system'
    | '/settings/theme'
    | '/states/empty'
    | '/states/error'
    | '/states/loading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BranchesRoute: typeof BranchesRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FilesRoute: typeof FilesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GradientBlurDemoRoute: typeof GradientBlurDemoRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationRoute: typeof OrganizationRoute
  PermissionsRoute: typeof PermissionsRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SearchRoute: typeof SearchRoute
  TeamsRoute: typeof TeamsRoute
  UsersRoute: typeof UsersRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  StatesEmptyRoute: typeof StatesEmptyRoute
  StatesErrorRoute: typeof StatesErrorRoute
  StatesLoadingRoute: typeof StatesLoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient-blur-demo': {
      id: '/gradient-blur-demo'
      path: '/gradient-blur-demo'
      fullPath: '/gradient-blur-demo'
      preLoaderRoute: typeof GradientBlurDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/empty': {
      id: '/states/empty'
      path: '/states/empty'
      fullPath: '/states/empty'
      preLoaderRoute: typeof StatesEmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/error': {
      id: '/states/error'
      path: '/states/error'
      fullPath: '/states/error'
      preLoaderRoute: typeof StatesErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/loading': {
      id: '/states/loading'
      path: '/states/loading'
      fullPath: '/states/loading'
      preLoaderRoute: typeof StatesLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuditLogsRoute: AuditLogsRoute,
  BranchesRoute: BranchesRoute,
  DepartmentsRoute: DepartmentsRoute,
  FilesRoute: FilesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GradientBlurDemoRoute: GradientBlurDemoRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationRoute: OrganizationRoute,
  PermissionsRoute: PermissionsRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SearchRoute: SearchRoute,
  TeamsRoute: TeamsRoute,
  UsersRoute: UsersRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  StatesEmptyRoute: StatesEmptyRoute,
  StatesErrorRoute: StatesErrorRoute,
  StatesLoadingRoute: StatesLoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
